### ISSUE TITLE
Utilize tl-header component in the GIFM UI to address the URL values in the top navigation

### ISSUE THREAD

**Issue by rmathew1011** [TAMULib/GIFMButtonUI#38]
Currently the links - Hours, Library and AskUs in https://library.tamu.edu/get-it currently has
```
<a href="#">Hours</a>
<a href="#">Libraries</a>
<a href="#">Ask Us</a>
```
brought in by the tamuheader directive.
Utilizing the tl-component could resolve this issue

**Comment by kaladay** [comment]
Ths appear to be solved based on PR #39
