### ISSUE TITLE
Coverage report not being sent to coveralls *

### ISSUE THREAD

**Issue by wwelling** [TAMULib/GIFMButtonUI#57]
16 09 2022 17:25:59.048:INFO [coveralls.io]: uploading...
16 09 2022 17:25:59.048:INFO [coveralls.io]: 422 --- {"message":"Couldn't find a repository matching this job.","error":true}

**Comment by jcreel** [comment]
This will be our prototype solution and we will lean on it for #224, #129, and #213.
